<?php
/*
 * MIT License
 *
 * Copyright (c) 2022 Mohamed EL QUCHIRI
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var \ElQuchiri\WebsiteSwitcher\Block\Website $block */
?>
<?php if (count($block->getWebsites())>0) : ?>
    <?php $id = $block->getCurrentWebsiteId() ?>
    <div class="switcher website switcher-website" data-ui-id="website-switcher" id="switcher-website<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Website')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-website-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="website-<?= $id ?>">
                    <span><?= $block->getCurrentWebsiteName() ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getWebsites() as $_lang) : ?>
                    <?php if ($block->getCurrentWebsiteId() !== $_lang->getId()) : ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="<?= $block->getWebsiteUrl($_lang->getId()) ?>">
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
