<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \ElQuchiri\WebsiteSwitcher\Block\Language $block */
?>
<?php if (count($block->getWebsites())>0) : ?>
    <?php $id = '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-fr">
                    <span><?= $block->getCurrentWebsiteName() ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getWebsites() as $_lang) : ?>
                    <?php if ($block->getCurrentWebsiteId() !== $_lang->getId()) : ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="<?= $block->getWebsiteUrl($_lang->getId()) ?>">
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
